# Development configuration
development:
  enabled: true

# Logging configuration
logging:
  level: "DEBUG"
  format: "text"
  output: "/var/log/dahdi_phone/dahdi_phone.log"  # Maps to ./logs via Docker volume
  rotation: "1 day"
  retention: "30 days"
