# dahdi-phone-api/config/default.yml

# Server configuration
server:
  host: "0.0.0.0"
  rest_port: 8000
  websocket_port: 8001
  workers: 1  # Single worker to prevent hardware access conflicts

# DAHDI configuration
dahdi:
  device: "/dev/dahdi/channel001"
  control: "/dev/dahdi/ctl"
  channel: 1
  audio:
    sample_rate: 8000
    channels: 1
    bit_depth: 16
  buffer_size: 320  # 20ms @ 8kHz/16-bit

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  output: "/var/log/dahdi_phone/api.log"
  rotation: "1 day"
  retention: "30 days"
  
# API configuration
api:
  rate_limit: 100  # requests per minute
  timeout: 30  # seconds
  max_connections: 1000

# WebSocket configuration
websocket:
  ping_interval: 30
  ping_timeout: 10
  max_message_size: 1048576  # 1MB

# Development configuration
development:
  enabled: false  # Set to false in production

# Security configuration
security:
  allowed_origins: ["*"]
  api_tokens: []  # List of valid API tokens
