# Development configuration
development:
  enabled: true
  mock_hardware: true

# Logging configuration
logging:
  level: "DEBUG"
  format: "json"
  output: "logs/dahdi_phone.log"  # Local logs directory
  rotation: "1 day"
  retention: "30 days"
